### ISSUE TITLE
HASSIO repository error

### ISSUE THREAD

**Issue by tstoykov** [kreativmonkey/hassio-addons#10]
19-12-10 22:50:36 INFO (MainThread) [hassio.store.git] Clone add-on https://github.com/kreativmonkey/hassio-addons repository
19-12-10 22:50:38 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/441b9bcc/homegear/config.json: required key not provided @ data['arch']. Got None
19-12-10 22:50:39 INFO (MainThread) [hassio.store] Load add-ons from store: 66 all - 1 new - 0 remove
19-12-10 22:52:26 INFO (MainThread) [hassio.store.git] Clone add-on https://github.com/kreativmonkey/hassio-addons/tree/master/homegear-rpi repository
19-12-10 22:52:26 ERROR (MainThread) [hassio.store.git] Can't clone https://github.com/kreativmonkey/hassio-addons/tree/master/homegear-rpi repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/kreativmonkey/hassio-addons/tree/master/homegear-rpi /data/addons/git/ab915b68
  stderr: 'Cloning into '/data/addons/git/ab915b68'...
fatal: repository 'https://github.com/kreativmonkey/hassio-addons/tree/master/homegear-rpi/' not found
'.
19-12-10 22:52:26 ERROR (MainThread) [hassio.store] Can't load from repository https://github.com/kreativmonkey/hassio-addons/tree/master/homegear-rpi
19-12-10 22:52:27 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/441b9bcc/homegear/config.json: required key not provided @ data['arch']. Got None

**Comment by kreativmonkey** [comment]
Hi @tstoykov do you have more information like wich raspberry-pi do you use, wich version of Home-Assistant are you installed? I can't reproduce this issue.

**Comment by tstoykov** [comment]
Hi, hassio 102.2 on rpi 3, hassos 2.12.

**Comment by tstoykov** [comment]
Just try ti install it again, this time with success! Thanks!

**Comment by kreativmonkey** [comment]
@tstoykov pleas try it with the new repository, i've changed a lot. now it should work fine!
