### ISSUE TITLE
This add-on is not available on your system.

### ISSUE THREAD

**Issue by libxmike** [kreativmonkey/hassio-addons#11]
Using Rpi 3 with HassOS 3.7, what do I need to change to be able to install?

**Comment by kreativmonkey** [comment]
I don't know your problem, i've installed HassOS 3.7 on my Rpi 3 and it works all fine. Do you have more information?

**Comment by libxmike** [comment]
> I don't know your problem, i've installed HassOS 3.7 on my Rpi 3 and it works all fine. Do you have more information?

Strange, I did add your repo to hassos again and now I can install.
Thanks for replying, I would not try again :)
I even ordered the HM-MOD-RPI-PCB to use the official Homematic CCU add-on (well it is just 20 EUR) and I have already CUL868 USB, well, I may use CUL868 on my QNAP NAS as backup.

**Comment by kreativmonkey** [comment]
If everything works fine, would you write a short how to at the github wiki?

**Comment by libxmike** [comment]
> If everything works fine, would you write a short how to at the github wiki?

But it is not really working fine, still have to figure out how to connect my thermostats to HA and control them. Searching for hours to find out the config settings is cumbersome and exhausting

**Comment by kreativmonkey** [comment]
I know, it is not perfect now, that depends on my small test setup. I've only used MAX! Thermostats for a while and actually i can only test it with one device.... 
That's why i need feedback and the changes you made so i can improve the add-on ;-). sorry for the trouble but it is a work in progress.

**Comment by libxmike** [comment]
yeah, I understand, I'm still working on it and try to figure out how to control it, I did years ago with FHEM and CUL868 which worked good but did not use it for years, I'll let you know when I get it to work.
