### ISSUE TITLE
Incorrect link to Homegear Docs

### ISSUE THREAD

**Issue by edgarveersel** [kreativmonkey/hassio-addons#14]
In the plugin description, there is a link to the Homegear docs, which refers to https://doc.homegear.eu/data/homegear/configuration.html

<img width="583" alt="Schermafbeelding 2020-03-08 om 09 14 36" src="https://user-images.githubusercontent.com/42475273/76159107-45ba3b00-611d-11ea-889e-9f4874fa5594.png">

However, that link does not work. It probably should be:
https://doc.homegear.eu/homegear/configuration.html

**Comment by kreativmonkey** [comment]
Thanks for reporting the wrong URL, it seems homegear has changed its url paths. I will fix it right now!
