### ISSUE TITLE
Homegear add-no no longer starts after 0.72.0 update on RPI4 (64 bits)

### ISSUE THREAD

**Issue by bjornhij** [kreativmonkey/hassio-addons#18]
Logs show:

id: ‘homegear’: no such user
id: ‘homegear’: no such user
chown: invalid user: ‘homegear:homegear’
cp: cannot stat '/var/lib/homegear.data/modules/*': No such file or directory
cp: cannot stat '/var/lib/homegear.data/flows/nodes/*': No such file or directory
chown: invalid user: ‘homegear:homegear’
chown: invalid user: ‘homegear:homegear’
homegear: unrecognized service
homegear-management: unrecognized service
homegear-influxdb: unrecognized service
03/10/21 23:39:48.258 Info: Shutting down shared object family module "Miscellaneous"...
03/10/21 23:39:48.258 Stopping UPnP server...
03/10/21 23:39:48.271 (Shutdown) => Stopping Event handler
03/10/21 23:39:48.273 (Shutdown) => Stopping MQTT client
03/10/21 23:39:48.669 (Shutdown) => Stopping RPC servers
03/10/21 23:39:48.735 RPC Server (Port 2001): Info: Waiting for threads to finish.
03/10/21 23:39:48.811 RPC Server (Port 2002): Info: Waiting for threads to finish.
03/10/21 23:39:48.835 RPC Server (Port 2003): Info: Waiting for threads to finish.
03/10/21 23:39:48.837 (Shutdown) => Stopping RPC client
03/10/21 23:39:48.837 (Shutdown) => Closing physical interfaces...

I tried rebuilding and reinstalling the add-on. Let me know if you need more information/logging.

**Comment by bjornhij** [comment]
--2021-03-11 19:52:05--  https://homegear.eu/downloads/nightlies/libhomegear-base_current_debian_stretch_arm64.deb
Resolving homegear.eu (homegear.eu)... 88.198.223.206, 2a01:4f8:bc:c00::206
Connecting to homegear.eu (homegear.eu)|88.198.223.206|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.homegear.eu//nightlies/libhomegear-base_current_debian_stretch_arm64.deb [following]
--2021-03-11 19:52:05--  https://downloads.homegear.eu//nightlies/libhomegear-base_current_debian_stretch_arm64.deb
Resolving downloads.homegear.eu (downloads.homegear.eu)... 88.198.223.206
Connecting to downloads.homegear.eu (downloads.homegear.eu)|88.198.223.206|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden

From installNightly.sh

**Comment by kreativmonkey** [comment]
you run this addon on raspberry pi 64bit befor the update? there was no architecture supported befor i've updated the addon. I think i know whats going wrong and will have a look on this the next days.

**Comment by bjornhij** [comment]
Correct, I have a raspberry 64 bits and did use the homegear add-on for months. I've now restored a backup from before the update:

# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# dpkg --print-architecture
arm64

# dpkg-query -l |grep homegear
ii  homegear                   0.8.0-3001                        arm64        Interface program to your smart home devices
ii  homegear-adminui           0.1.0-224                         all          Provides an administrative user interface for Homegear.
ii  homegear-beckhoff          0.8.0-3001                        arm64        Beckhoff module for Homegear
ii  homegear-ccu               0.8.0-3001                        arm64        CCU module for Homegear
ii  homegear-easy-licensing    0.8.0-3001                        arm64        EASY Smarthome licensing module for Homegear
ii  homegear-easycam           0.8.0-3001                        arm64        EASYLed module for Homegear
ii  homegear-easyled           0.8.0-3001                        arm64        EASYLed module for Homegear
ii  homegear-easyled2          0.8.0-3001                        arm64        EASYLed module for Homegear
ii  homegear-enocean           0.8.0-3001                        arm64        EnOcean module for Homegear
ii  homegear-homematicbidcos   0.8.0-3001                        arm64        HomeMatic BidCoS module for Homegear
ii  homegear-homematicwired    0.8.0-3001                        arm64        HomeMatic BidCoS module for Homegear
ii  homegear-influxdb          0.8.0-3001                        arm64        Passes variable changes in Homegear to InfluxDB
ii  homegear-insteon           0.8.0-3001                        arm64        HomeMatic BidCoS module for Homegear
ii  homegear-intertechno       0.8.0-3001                        arm64        Intertechno module for Homegear
ii  homegear-ipcam             0.8.0-3001                        arm64        IPCam module for Homegear
ii  homegear-knx               0.8.0-3001                        arm64        KNX module for Homegear
ii  homegear-kodi              0.8.0-3001                        arm64        Kodi module for Homegear
ii  homegear-licensing         0.8.0-3001                        arm64        Default licensing module for Homegear
ii  homegear-management        0.8.0-3001                        arm64        Management service for Homegear
ii  homegear-max               0.8.0-3001                        arm64        HomeMatic BidCoS module for Homegear
ii  homegear-mbus              0.8.0-3001                        arm64        M-Bus module for Homegear
ii  homegear-nodes-core        0.8.0-3001                        arm64        Core nodes for Homegear's Node-BLUE
ii  homegear-nodes-extra       0.8.0-3001                        arm64        Extra nodes for Homegear's Node-BLUE
ii  homegear-philipshue        0.8.0-3001                        arm64        Philips Hue module for Homegear
ii  homegear-rs2w              0.8.0-3001                        arm64        Renkforce module for Homegear
ii  homegear-rsl               0.8.0-3001                        arm64        Conrad RSL module for Homegear
ii  homegear-sonos             0.8.0-3001                        arm64        HomeMatic BidCoS module for Homegear
ii  homegear-webssh            0.8.0-3001                        arm64        Management service for Homegear
ii  homegear-zwave             0.8.0-3001                        arm64        Z-Wave module for Homegear
ii  libhomegear-base           0.8.0-3001                        arm64        Base library for Homegear
ii  libhomegear-ipc            0.1.2-40                          arm64        IPC library for Homegear
ii  libhomegear-node           0.1.7-51                          arm64        Node library for Homegear
ii  python3-homegear           1.0.14-1                          arm64        Python module for Homegear

**Comment by bjornhij** [comment]
Could the problem be homegear is no longer publishing arm64 packages for stretch?

https://homegear.eu/downloads.html?version=0.8
