### ISSUE TITLE
Repository not showing up

### ISSUE THREAD

**Issue by capfirepants** [kreativmonkey/hassio-addons#7]
Hi
Im trying to add the repository as an addon but get the following error:
`19-04-10 07:24:44 INFO (MainThread) [hassio.addons.git] Clone add-on https://github.com/kreativmonkey/hassio-addons repository
19-04-10 07:24:46 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/git/441b9bcc/homegear/config.json: required key not provided @ data['arch']. Got None
19-04-10 07:24:46 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/git/441b9bcc/homegear-rpi/config.json: required key not provided @ data['arch']. Got None`
Thie prevents the addon from being shown.

**Comment by blazkom** [comment]
I can confirm. I have same problem

**Comment by hiol83** [comment]
Same problem here:

19-12-04 02:37:57 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/441b9bcc/homegear-rpi/config.json: required key not provided @ data['arch']. Got None
19-12-04 02:37:57 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/441b9bcc/homegear/config.json: required key not provided @ data['arch']. Got None

**Comment by kreativmonkey** [comment]
This issue is closed by adding the arch tag on config.json
